version: 0.0.1
achievements:
  - achievement:
      name: Shooting Star
      icon: https://github.com/vauntdev/example/blob/master/.vaunt/shooting_star.png
      description: Awarded for staring our repository, make a wish!
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true
  - achievement:
      name: Every Bit Counts
      icon: https://github.com/vauntdev/example/blob/master/.vaunt/every_bit_counts.png
      description: No commit is to small!
      triggers:
        - trigger:
            actor: author
            action: commit
            condition: count() >= 1
  - achievement:
      name: Pull Request Hero
      icon:https://github.com/vauntdev/example/blob/master/.vaunt/pull_request_hero.png
      description: You're a PR hero, rock on!
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: merged = true
  - achievement:
      name: Closer
      icon: https://github.com/vauntdev/example/blob/master/.vaunt/closer.png
      description: Only closers get coffee!
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: closed = true
